desc 'TODO'
task create_specialities: :environment do
  @specialities = [{title: 'Лечебное дело, Педиатрия', parent: nil, level: 1},
                  {title: 'Медико-профилактическое дело', parent: nil, level: 1},
                  {title: 'Стоматология', parent: nil, level: 1},
                  {title: 'Фармация', parent: nil, level: 1},
                  {title: 'Сестринское дело', parent: nil, level: 1},
                  {title: 'Медицинская биохимия', parent: nil, level: 1},
                  {title: 'Медицинская биофизика, Медицинская кибернетика', parent: nil, level: 1},
                      {title: 'Акушерство и гинекология', parent: 1, level: 2},
                      {title: 'Анестезиология и реаниматология', parent: 1, level: 2},
                      {title: 'Дерматовенерология', parent: 1, level: 2},
                      {title: 'Детская хирургия', parent: 1, level: 2},
                      {title: 'Генетика', parent: 1, level: 2},
                      {title: 'Инфекционные болезни', parent: 1, level: 2},
                      {title: 'Клиническая лабораторная диагностика', parent: 1, level: 2},
                      {title: 'Неврология', parent: 1, level: 2},
                      {title: 'Общая врачебная практика', parent: 1, level: 2},
                      {title: 'Онкология', parent: 1, level: 2},
                      {title: 'Организация здравоохранения и общественное здоровье', parent: 1, level: 2},
                      {title: 'Оториноларингология', parent: 1, level: 2},
                      {title: 'Офтальмология', parent: 1, level: 2},
                      {title: 'Патологическая анатомия', parent: 1, level: 2},
                      {title: 'Педиатрия', parent: 1, level: 2},
                      {title: 'Психиатрия', parent: 1, level: 2},
                      {title: 'Рентгенология', parent: 1, level: 2},
                      {title: 'Скорая медицинская помощь', parent: 1, level: 2},
                      {title: 'Судебно-медицинская экспертиза', parent: 1, level: 2},
                      {title: 'Терапия', parent: 1, level: 2},
                      {title: 'Травматология и ортопедия', parent: 1, level: 2},
                      {title: 'Фтизиатрия', parent: 1, level: 2},
                      {title: 'Хирургия', parent: 1, level: 2},
                      {title: 'Эндокринология', parent: 1, level: 2},
                      {title: 'Клиническая лабораторная диагностика', parent: 2, level: 2},
                      {title: 'Общая гигиена', parent: 2, level: 2},
                      {title: 'Социальная гигиена и организация госсанэпидслужбы', parent: 2, level: 2},
                      {title: 'Эпидемиология', parent: 2, level: 2},
                      {title: 'Стоматология общей практики', parent: 3, level: 2},
                      {title: 'Клиническая лабораторная диагностика', parent: 3, level: 2},
                      {title: 'Управление и экономика фармации', parent: 4, level: 2},
                      {title: 'Фармацевтическая технология', parent: 4, level: 2},
                      {title: 'Фармацевтическая химия и фармакогнозия', parent: 4, level: 2},
                      {title: 'Управление сестринской деятельностью', parent: 5, level: 2},
                      {title: 'Генетика', parent: 6, level: 2},
                      {title: 'Клиническая лабораторная диагностика', parent: 6, level: 2},
                      {title: 'Судебно-медицинская экспертиза', parent: 6, level: 2},
                      {title: 'Клиническая лабораторная диагностика', parent: 7, level: 2},
                      {title: 'Рентгенология', parent: 7, level: 2},
                      {title: 'Функциональная диагностика', parent: 7, level: 2},
                      {title: 'Ультразвуковая диагностика', parent: 7, level: 2}
                  ]
  Speciality.create!(@specialities)
end
